import { NORMAL_SYMBOLS, type SymbolId } from '../types';
export const GAME_CONFIG = {
  rows: 6,
  columns: 6,
  minClusterSize: 3,
  maxCascades: 20,
  normalSymbols: NORMAL_SYMBOLS,
  spawnWeights: {
    pink: 20,
    yellow: 20,
    green: 20,
    purple: 20,
    aqua: 20,
    fire: 0,
    bonus: 0.7,
  } satisfies Record<SymbolId, number>,
  specialSpawn: { fireMinClusterSize: 5, fireChance: 0.3 },
  baseScores: { 3: 30, 4: 60, 5: 120, 6: 200, 7: 300 } as Record<number, number>,
  largeClusterBase: 300,
  largeClusterThreshold: 7,
  largeClusterIncrement: 100,
  comboMultipliers: [1, 1.2, 1.5, 2, 3, 5],
  comboLabels: ['GOOD', 'GREAT', 'AMAZING', 'JELLY COMBO', 'SUPER JELLY', 'LAB FEVER'],
  explosionCellScore: 10,
  bonusTarget: 3,
  initialPlays: 10,
  // PHASE 1 MOCK ONLY. Never use this formula for a production POINTS ledger.
  mockPointDivisor: 100,
  maxInitialRerolls: 2,
  animation: {
    starting: 160,
    spawning: 850,
    matching: 580,
    popping: 400,
    falling: 470,
    refilling: 510,
    resolving: 160,
    complete: 450,
    fastFactor: 0.55,
    reducedFactor: 0.65,
    columnStagger: 24,
    landingOvershoot: 0.025,
  },
} as const;
